openapi: 3.0.3
info:
  title: ARS Backend
servers:
  - url: "/api/v1"
components:
  schemas:
    GetResponse:
      type: object
      properties:
        count:
          type: number
        rows:
          type: array
  securitySchemes:
    auth_token:
      type: http
      in: header
      name: Authorization
      scheme: Bearer
