openapi: 3.0.3
info:
  title: ARS Backend
servers:
  -
    url: /api/{version}
    description: API endpoints
    variables:
      version:
        default: v1
        description: API Version
        enum:
          - v1
          - v2

components:
  schemas:
    GetResponse:
      type: object
      properties:
        count:
          type: number
        rows:
          type: array
  securitySchemes:
    auth_token:
      type: http
      in: header
      name: Authorization
      scheme: Bearer
